//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngwmapp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ngwmapp.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEAM WORK.
        /// </summary>
        internal static string CAFourSub {
            get {
                return ResourceManager.GetString("CAFourSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All-in-one Tool.
        /// </summary>
        internal static string CAFourSubFour {
            get {
                return ResourceManager.GetString("CAFourSubFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Management &amp; Administration.
        /// </summary>
        internal static string CAFourSubOne {
            get {
                return ResourceManager.GetString("CAFourSubOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Knowledge Sharing.
        /// </summary>
        internal static string CAFourSubThree {
            get {
                return ResourceManager.GetString("CAFourSubThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collective Data Capture.
        /// </summary>
        internal static string CAFourSubTwo {
            get {
                return ResourceManager.GetString("CAFourSubTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADVANTAGES.
        /// </summary>
        internal static string CAOneSub {
            get {
                return ResourceManager.GetString("CAOneSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent Site Management.
        /// </summary>
        internal static string CAOneSubFour {
            get {
                return ResourceManager.GetString("CAOneSubFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Quality Management.
        /// </summary>
        internal static string CAOneSubOne {
            get {
                return ResourceManager.GetString("CAOneSubOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joint Welding Process Approval.
        /// </summary>
        internal static string CAOneSubThree {
            get {
                return ResourceManager.GetString("CAOneSubThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Libraries.
        /// </summary>
        internal static string CAOneSubTwo {
            get {
                return ResourceManager.GetString("CAOneSubTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing multiple manufacturing sites, either within a corporation or with supply chain management, was never easier. With a multi-site license, you can define how many of the locations shall be grouped in a central administration or are operating independently. Central administration provides the opportunity to leverage experience, share approvals, and managing a joint set of library entrances. Even though every central administration member shares its site information, the ownership of welding approvals r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CAPara {
            get {
                return ResourceManager.GetString("CAPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETWORKING &amp; TEAMS.
        /// </summary>
        internal static string CAThreeSub {
            get {
                return ResourceManager.GetString("CAThreeSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control of Standards.
        /// </summary>
        internal static string CAThreeSubFour {
            get {
                return ResourceManager.GetString("CAThreeSubFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Site Expert Integration.
        /// </summary>
        internal static string CAThreeSubOne {
            get {
                return ResourceManager.GetString("CAThreeSubOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Identity.
        /// </summary>
        internal static string CAThreeSubThree {
            get {
                return ResourceManager.GetString("CAThreeSubThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string CAThreeSubTwo {
            get {
                return ResourceManager.GetString("CAThreeSubTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central application.
        /// </summary>
        internal static string CATitle {
            get {
                return ResourceManager.GetString("CATitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENHANCE CLARITY.
        /// </summary>
        internal static string CATwoSub {
            get {
                return ResourceManager.GetString("CATwoSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increased Customre Trust.
        /// </summary>
        internal static string CATwoSubFour {
            get {
                return ResourceManager.GetString("CATwoSubFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teamwork without Borders.
        /// </summary>
        internal static string CATwoSubOne {
            get {
                return ResourceManager.GetString("CATwoSubOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centralizing Approval Agnecies.
        /// </summary>
        internal static string CATwoSubThree {
            get {
                return ResourceManager.GetString("CATwoSubThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Control for Base &amp; Filler Material.
        /// </summary>
        internal static string CATwoSubTwo {
            get {
                return ResourceManager.GetString("CATwoSubTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The world is becoming increasingly interconnected and brings together experts from all over the world. Project clarity must be managed effectively across international borders, and language barriers must become a non-critical factor. All projects should be focusing on solutions that support a cost-effective conversion of engineering demands, code compliance, quality objectives, savings, and timelines that satisfy the customer..
        /// </summary>
        internal static string contentDescDes {
            get {
                return ResourceManager.GetString("contentDescDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Powerful Application.
        /// </summary>
        internal static string contentDescTitle {
            get {
                return ResourceManager.GetString("contentDescTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string footerContactUsTag {
            get {
                return ResourceManager.GetString("footerContactUsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved. Our Terms &amp; Conditions apply!.
        /// </summary>
        internal static string footerEnd {
            get {
                return ResourceManager.GetString("footerEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string footerFourSub {
            get {
                return ResourceManager.GetString("footerFourSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQs.
        /// </summary>
        internal static string footerFourSubOne {
            get {
                return ResourceManager.GetString("footerFourSubOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        internal static string footerFourSubThree {
            get {
                return ResourceManager.GetString("footerFourSubThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpful Information.
        /// </summary>
        internal static string footerFourSubTwo {
            get {
                return ResourceManager.GetString("footerFourSubTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Care.
        /// </summary>
        internal static string footerOneSub {
            get {
                return ResourceManager.GetString("footerOneSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelation &amp; Change.
        /// </summary>
        internal static string footerOneSubOne {
            get {
                return ResourceManager.GetString("footerOneSubOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string footerOneSubThree {
            get {
                return ResourceManager.GetString("footerOneSubThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string footerOneSubTwo {
            get {
                return ResourceManager.GetString("footerOneSubTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string footerThreeSub {
            get {
                return ResourceManager.GetString("footerThreeSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string footerThreeSubOne {
            get {
                return ResourceManager.GetString("footerThreeSubOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register/Purchase.
        /// </summary>
        internal static string footerThreeSubTwo {
            get {
                return ResourceManager.GetString("footerThreeSubTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application with global accessibility and global collaboration.
        /// </summary>
        internal static string footerTitle {
            get {
                return ResourceManager.GetString("footerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insite GWM.
        /// </summary>
        internal static string footerTwoSub {
            get {
                return ResourceManager.GetString("footerTwoSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About GWM.
        /// </summary>
        internal static string footerTwoSubOne {
            get {
                return ResourceManager.GetString("footerTwoSubOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers.
        /// </summary>
        internal static string footerTwoSubThree {
            get {
                return ResourceManager.GetString("footerTwoSubThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why GWM.
        /// </summary>
        internal static string footerTwoSubTwo {
            get {
                return ResourceManager.GetString("footerTwoSubTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string languageEight {
            get {
                return ResourceManager.GetString("languageEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        internal static string languageEleven {
            get {
                return ResourceManager.GetString("languageEleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string languageFive {
            get {
                return ResourceManager.GetString("languageFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutuch.
        /// </summary>
        internal static string languageFour {
            get {
                return ResourceManager.GetString("languageFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string languageNine {
            get {
                return ResourceManager.GetString("languageNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string languageOne {
            get {
                return ResourceManager.GetString("languageOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string languageSelection {
            get {
                return ResourceManager.GetString("languageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string languageSeven {
            get {
                return ResourceManager.GetString("languageSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        internal static string languageSix {
            get {
                return ResourceManager.GetString("languageSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string languageTen {
            get {
                return ResourceManager.GetString("languageTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        internal static string languageThree {
            get {
                return ResourceManager.GetString("languageThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        internal static string languageTwo {
            get {
                return ResourceManager.GetString("languageTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About GWM.
        /// </summary>
        internal static string menuFour {
            get {
                return ResourceManager.GetString("menuFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string menuOne {
            get {
                return ResourceManager.GetString("menuOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string menuThree {
            get {
                return ResourceManager.GetString("menuThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string menuTwo {
            get {
                return ResourceManager.GetString("menuTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless teamwork with language options.
        /// </summary>
        internal static string resultFourDes {
            get {
                return ResourceManager.GetString("resultFourDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance clarity.
        /// </summary>
        internal static string resultFourTitle {
            get {
                return ResourceManager.GetString("resultFourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspire customers to join your team.
        /// </summary>
        internal static string resultOneDes {
            get {
                return ResourceManager.GetString("resultOneDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase sales.
        /// </summary>
        internal static string resultOneTitle {
            get {
                return ResourceManager.GetString("resultOneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add experts on-the-go.
        /// </summary>
        internal static string resultThreeDes {
            get {
                return ResourceManager.GetString("resultThreeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut project time.
        /// </summary>
        internal static string resultThreeTitle {
            get {
                return ResourceManager.GetString("resultThreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive results with our SaaS application.
        /// </summary>
        internal static string resultTitle {
            get {
                return ResourceManager.GetString("resultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce the frequent site visits.
        /// </summary>
        internal static string resultTwoDes {
            get {
                return ResourceManager.GetString("resultTwoDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease travel &amp; cost.
        /// </summary>
        internal static string resultTwoTitle {
            get {
                return ResourceManager.GetString("resultTwoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welder Performance Qualification Records.
        /// </summary>
        internal static string weldingCodeEightDes {
            get {
                return ResourceManager.GetString("weldingCodeEightDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preliminary WPS.
        /// </summary>
        internal static string weldingCodeFiveDes {
            get {
                return ResourceManager.GetString("weldingCodeFiveDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string weldingCodeFour {
            get {
                return ResourceManager.GetString("weldingCodeFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We implement your welding specification.
        /// </summary>
        internal static string weldingCodeFourDes {
            get {
                return ResourceManager.GetString("weldingCodeFourDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Society of Mechanical Engineers.
        /// </summary>
        internal static string weldingCodeOneDes {
            get {
                return ResourceManager.GetString("weldingCodeOneDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welding Procedure Specification.
        /// </summary>
        internal static string weldingCodeSevenDes {
            get {
                return ResourceManager.GetString("weldingCodeSevenDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welding Procedure Qualification Records.
        /// </summary>
        internal static string weldingCodeSixDes {
            get {
                return ResourceManager.GetString("weldingCodeSixDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Including EN ISO editions approved through CEN.
        /// </summary>
        internal static string weldingCodeThreeDes {
            get {
                return ResourceManager.GetString("weldingCodeThreeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Welding Society.
        /// </summary>
        internal static string weldingCodeTwoDes {
            get {
                return ResourceManager.GetString("weldingCodeTwoDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your business is most important. We designed this application to support your requirements in any way possible. Adding welding codes from other countries, or customizing the range of qualifications to your needs, is part of our portfolio..
        /// </summary>
        internal static string weldingDes {
            get {
                return ResourceManager.GetString("weldingDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welding Codes &amp; Customization.
        /// </summary>
        internal static string weldingTitle {
            get {
                return ResourceManager.GetString("weldingTitle", resourceCulture);
            }
        }
    }
}
